#!/bin/bash
# === Ablation A7: all Miles enhancements on (upper-bound reference) ===
# Combines layer-scale + ratio-clip + margin-cap-with-anneal +
# shiftmask(binary) + boundary weighting + flip-fallback.
# This is the closest match to the production "stabilized + flipguard-wide"
# preset from legacy scripts, ported to lr_mult=1e2.
#SBATCH --job-name=miles-off2-pr2-A7-klpost1e2-allon
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --gres=gpu:8
#SBATCH --account=k2m
#SBATCH --qos=lowprio
#SBATCH --partition=lowprio
#SBATCH --exclusive
#SBATCH --output=/mnt/weka/home/hongyi.wang/workspace/rlhf/miles/logs_tmp/sbatch/%x-%J/%N.%J.%t.log
#SBATCH --error=/mnt/weka/home/hongyi.wang/workspace/rlhf/miles/logs_tmp/sbatch/%x-%J/%N.%J.%t.err
#SBATCH --open-mode=append

set -euo pipefail

BASE_SCRIPT="/mnt/weka/home/hongyi.wang/workspace/rlhf/miles/scripts_mine/train/PREEXP-qwen3-30B-A3B-Base/off2/launch/hy-sbatch-8nodes.sh"
export RUN_POSTFIX="${RUN_POSTFIX:-off2-pr2-A7-klpost1e2-allon}"
export RESOURCE_LAYOUT="${RESOURCE_LAYOUT:-disagg}"
export ACTOR_NUM_NODES="${ACTOR_NUM_NODES:-1}"
export NUM_STEPS_PER_ROLLOUT="${NUM_STEPS_PER_ROLLOUT:-2}"
export NUM_ROLLOUT="${NUM_ROLLOUT:-540}"
export ENABLE_ASYNC_TRAIN="${ENABLE_ASYNC_TRAIN:-1}"
export ENABLE_KEEP_OLD_ACTOR="${ENABLE_KEEP_OLD_ACTOR:-1}"
export ENABLE_AUTO_CKPT_EVAL="${ENABLE_AUTO_CKPT_EVAL:-1}"
export AUTO_CKPT_EVAL_BENCHMARKS="${AUTO_CKPT_EVAL_BENCHMARKS:-aime2024}"
export UPDATE_WEIGHTS_INTERVAL="${UPDATE_WEIGHTS_INTERVAL:-1}"
export USE_MILES_ROUTER="${USE_MILES_ROUTER:-1}"
export USE_ROUTING_REPLAY="${USE_ROUTING_REPLAY:-1}"
export USE_ROLLOUT_ROUTING_REPLAY="${USE_ROLLOUT_ROUTING_REPLAY:-0}"
export ENABLE_PREDICTIVE_ROUTING_REPLAY="${ENABLE_PREDICTIVE_ROUTING_REPLAY:-1}"
export BIAS_PREDICTOR_LOSS_TYPE="${BIAS_PREDICTOR_LOSS_TYPE:-kl-post}"
export BIAS_PREDICTOR_LR_MULT="${BIAS_PREDICTOR_LR_MULT:-1e2}"
export PREDICTIVE_DOWNSAMPLE_BATCH_SIZE="${PREDICTIVE_DOWNSAMPLE_BATCH_SIZE:-2}"
export PREDICTIVE_DOWNSAMPLE_MAX_LEN_LIMIT="${PREDICTIVE_DOWNSAMPLE_MAX_LEN_LIMIT:-8192}"
export PREDICTIVE_MAX_TOTAL_TOKENS="${PREDICTIVE_MAX_TOTAL_TOKENS:-4096}"
export PREDICTIVE_STORAGE_DTYPE="${PREDICTIVE_STORAGE_DTYPE:-fp32}"
# --- All enhancements on ---
export PREDICTIVE_LAYER_SCALE_SCHEDULE="${PREDICTIVE_LAYER_SCALE_SCHEDULE:-sqrt_decay}"
export PREDICTIVE_LAYER_SCALE_MIN="${PREDICTIVE_LAYER_SCALE_MIN:-0.5}"
export PREDICTIVE_MAX_DELTA_TO_OLD_RATIO="${PREDICTIVE_MAX_DELTA_TO_OLD_RATIO:-0.015}"
export PREDICTIVE_MAX_DELTA_TO_TOPK_MARGIN_RATIO="${PREDICTIVE_MAX_DELTA_TO_TOPK_MARGIN_RATIO:-1.0}"
export PREDICTIVE_MAX_DELTA_TO_TOPK_MARGIN_RATIO_FINAL="${PREDICTIVE_MAX_DELTA_TO_TOPK_MARGIN_RATIO_FINAL:-1.5}"
export PREDICTIVE_TOPK_MARGIN_RATIO_ANNEAL_START_ROLLOUT="${PREDICTIVE_TOPK_MARGIN_RATIO_ANNEAL_START_ROLLOUT:-80}"
export PREDICTIVE_TOPK_MARGIN_RATIO_ANNEAL_END_ROLLOUT="${PREDICTIVE_TOPK_MARGIN_RATIO_ANNEAL_END_ROLLOUT:-160}"
export PREDICTIVE_MAX_HIDDEN_SHIFT_RELATIVE_NORM="${PREDICTIVE_MAX_HIDDEN_SHIFT_RELATIVE_NORM:-0.02}"
export PREDICTIVE_HIDDEN_SHIFT_WEIGHT_MODE="${PREDICTIVE_HIDDEN_SHIFT_WEIGHT_MODE:-binary}"
export PREDICTIVE_BOUNDARY_LOSS_MAX_WEIGHT="${PREDICTIVE_BOUNDARY_LOSS_MAX_WEIGHT:-4.0}"
export PREDICTIVE_BOUNDARY_LOSS_MIN_MARGIN="${PREDICTIVE_BOUNDARY_LOSS_MIN_MARGIN:-1e-4}"
export PREDICTIVE_MIN_POST_TOPK_MARGIN_FOR_FLIP="${PREDICTIVE_MIN_POST_TOPK_MARGIN_FOR_FLIP:-0.05}"

exec bash "${BASE_SCRIPT}"
